/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berry;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;

/**
 *
 * @author Ben
 */
public class berryUI extends javax.swing.JFrame {

    /**
     * Creates new form berryUI
     */
    boolean graphOptsVis = false;
    boolean graphCust = true;
    boolean recording = false;
    int options = 0;
    String[] listData = 
    {"Ben: Yes",
    "Glen: The answer is no",
    "Hannah: Who knows",
    "Mat: I am lorde",
    "Anthony: I am sure it is yes",
    "Joe: no",
    "Hose: Maybe",
    "Leon: Yes",
    "Ryan: Def yes"}; //will be suplies by zoom later, temp data
    DefaultListModel listModel = new DefaultListModel();
    ArrayList<Integer> selections = new ArrayList<Integer>();
    List<Double> scores = new ArrayList<Double>();
    public berryUI() {
        initComponents();
        graphOptionsPanel.setVisible(false);
        previewPanel.setVisible(false);
        chatList.setListData(listData);
        for (int i = 0; i<listData.length; i++) {
            listModel.addElement(listData[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	graph = new GraphPanel(scores);
        graphPagePanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        vAxisText = new javax.swing.JLabel();
        graphTitleText = new javax.swing.JLabel();
        hAxisText = new javax.swing.JLabel();
        custimizeGraphPanel = new javax.swing.JPanel();
        titleIndicator = new javax.swing.JLabel();
        vAxisIndicator = new javax.swing.JLabel();
        hAxisIndicator = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        vAxisTitleField = new javax.swing.JTextField();
        hAxistTitleField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        hideMenu = new javax.swing.JButton();
        mainPagePanel = new javax.swing.JPanel();
        visualizeButton = new javax.swing.JButton();
        recordAnswersButton = new javax.swing.JButton();
        graphOptionsPanel = new javax.swing.JPanel();
        option1Button = new javax.swing.JButton();
        option2Button = new javax.swing.JButton();
        option3Button = new javax.swing.JButton();
        option4Button = new javax.swing.JButton();
        moreGraphsButton = new javax.swing.JButton();
        chatPanel = new javax.swing.JPanel();
        chatScrollPane = new javax.swing.JScrollPane();
        chatList = new javax.swing.JList<>();
        sendMessageButton = new javax.swing.JButton();
        chatTitleText = new javax.swing.JLabel();
        sendMessageForm = new javax.swing.JTextField();
        previewPanel = new javax.swing.JPanel();
        selectGraphButton = new javax.swing.JButton();

        graphPagePanel.setBackground(new java.awt.Color(255, 255, 255));
        graphPagePanel.setPreferredSize(new java.awt.Dimension(456, 308));
        graphPagePanel.setRequestFocusEnabled(false);

        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        graphPanel.setBackground(new java.awt.Color(255, 255, 255));
        vAxisText.setText("<html>Verical<br>Axis<br>Titile</html>");

        graphTitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        graphTitleText.setForeground(new java.awt.Color(51, 0, 51));
        graphTitleText.setText("Graph Title");

        hAxisText.setText("Horizontal Axis Title");

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(graphTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(vAxisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(graph)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hAxisText)
                .addGap(166, 166, 166))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(vAxisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(graph)
                .addGap(66, 66, 66)
                .addComponent(hAxisText)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        custimizeGraphPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleIndicator.setText("Title:");

        vAxisIndicator.setText("Vertical Axis title:");

        hAxisIndicator.setText("Horizontal Axis title:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout custimizeGraphPanelLayout = new javax.swing.GroupLayout(custimizeGraphPanel);
        custimizeGraphPanel.setLayout(custimizeGraphPanelLayout);
        custimizeGraphPanelLayout.setHorizontalGroup(
            custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custimizeGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hAxisIndicator)
                    .addComponent(vAxisIndicator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vAxisTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(titleField)
                    .addComponent(hAxistTitleField))
                .addGap(38, 38, 38) 
                .addComponent(submitButton)
                .addGap(246, 246, 246))
        );
        custimizeGraphPanelLayout.setVerticalGroup(
            custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custimizeGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleIndicator)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vAxisIndicator)
                    .addComponent(vAxisTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custimizeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hAxisIndicator)
                    .addComponent(hAxistTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hideMenu.setText("Hide Menu");
        hideMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphPagePanelLayout = new javax.swing.GroupLayout(graphPagePanel);
        graphPagePanel.setLayout(graphPagePanelLayout);
        graphPagePanelLayout.setHorizontalGroup(
            graphPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPagePanelLayout.createSequentialGroup()
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(graphPagePanelLayout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(custimizeGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(hideMenu)
                .addGap(18, 18, 18))
        );
        graphPagePanelLayout.setVerticalGroup(
            graphPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPagePanelLayout.createSequentialGroup()
                .addGroup(graphPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custimizeGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(graphPagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hideMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);

        mainPagePanel.setBackground(new java.awt.Color(255, 255, 255));

        visualizeButton.setText("Visualize");
        visualizeButton.setToolTipText("Visualize Collected Data as one of our graph options");
        visualizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeButtonActionPerformed(evt);
            }
        });

        recordAnswersButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ben\\Pictures\\player_record2.png")); // NOI18N
        recordAnswersButton.setText("<html><p>Record<br>Answers</p></html>\n");
        recordAnswersButton.setToolTipText("Start recording the chat");
        recordAnswersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recordAnswersButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        recordAnswersButton.setOpaque(false);
        recordAnswersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAnswersButtonActionPerformed(evt);
            }
        });

        graphOptionsPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                graphOptionsPanelPropertyChange(evt);
            }
        });

        option1Button.setText("Bar Graph");
        option1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ButtonActionPerformed(evt);
            }
        });

        option2Button.setText("Line Graph");
        option2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ButtonActionPerformed(evt);
            }
        });

        option3Button.setText("Set Diagram");
        option3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ButtonActionPerformed(evt);
            }
        });

        option4Button.setText("Pie Chart");
        option4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4ButtonActionPerformed(evt);
            }
        });

        moreGraphsButton.setText(">");
        moreGraphsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreGraphsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphOptionsPanelLayout = new javax.swing.GroupLayout(graphOptionsPanel);
        graphOptionsPanel.setLayout(graphOptionsPanelLayout);
        graphOptionsPanelLayout.setHorizontalGroup(
            graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphOptionsPanelLayout.createSequentialGroup()
                .addGroup(graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(option3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(option2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(option4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(moreGraphsButton)
                .addGap(0, 0, 0))
        );
        graphOptionsPanelLayout.setVerticalGroup(
            graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphOptionsPanelLayout.createSequentialGroup()
                .addGroup(graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(graphOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moreGraphsButton)
                .addGap(59, 59, 59))
        );

        chatPanel.setBackground(new java.awt.Color(255, 255, 255));

        chatScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        chatScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        chatScrollPane.setAutoscrolls(true);

        chatList.setModel(listModel);
        chatList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatListMouseClicked(evt);
            }
        });
        chatScrollPane.setViewportView(chatList);

        sendMessageButton.setText("Send");
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        chatTitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chatTitleText.setText("Zoom Chat");

        sendMessageForm.setText("Send Message");
        sendMessageForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chatPanelLayout.createSequentialGroup()
                        .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chatPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chatTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(chatPanelLayout.createSequentialGroup()
                                .addComponent(sendMessageForm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendMessageButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chatTitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageButton)
                    .addComponent(sendMessageForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        selectGraphButton.setText("Select");
        selectGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGraphButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previewPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectGraphButton)
                .addContainerGap())
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previewPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(selectGraphButton))
        );

        javax.swing.GroupLayout mainPagePanelLayout = new javax.swing.GroupLayout(mainPagePanel);
        mainPagePanel.setLayout(mainPagePanelLayout);
        mainPagePanelLayout.setHorizontalGroup(
            mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPagePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPagePanelLayout.createSequentialGroup()
                        .addComponent(recordAnswersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(visualizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mainPagePanelLayout.setVerticalGroup(
            mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPagePanelLayout.createSequentialGroup()
                .addGroup(mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPagePanelLayout.createSequentialGroup()
                        .addComponent(graphOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPagePanelLayout.createSequentialGroup()
                        .addGroup(mainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visualizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordAnswersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 11, Short.MAX_VALUE))
        );

        recordAnswersButton.getAccessibleContext().setAccessibleDescription("Start recording the chat, answers will be collected and automatically fed into the graphs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeButtonActionPerformed
        // TODO add your handling code here:
        //Visualize button was pressed
        if (graphOptsVis == false) {
            graphOptionsPanel.setVisible(true);
            graphOptsVis = true;
        }
        else {
            graphOptionsPanel.setVisible(false);
            graphOptsVis = false;
        }
    }//GEN-LAST:event_visualizeButtonActionPerformed

    private void sendMessageFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageFormActionPerformed
        // TODO add your handling code here:
        System.out.println(sendMessageForm.getAccessibleContext());
        
    }//GEN-LAST:event_sendMessageFormActionPerformed

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        // TODO add your handling code here:
        listModel.addElement("Host: " + sendMessageForm.getText());
        chatList.setModel(listModel);
        sendMessageForm.setText("");
    }//GEN-LAST:event_sendMessageButtonActionPerformed

    private void graphOptionsPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_graphOptionsPanelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_graphOptionsPanelPropertyChange

    private void option4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ButtonActionPerformed
        // TODO add your handling code here:
        if (options == 0){
            graphOptionsPanel.setVisible(false);
            previewPanel.setVisible(true);
            option4Button.setText("Pie Chart: Preview");
            graphOptsVis = false;
        }
        else{
            graphOptionsPanel.setVisible(false);
            previewPanel.setVisible(true);
            option4Button.setText("Mind Map: Preview");
            graphOptsVis = false;
        }
    }//GEN-LAST:event_option4ButtonActionPerformed

    private void option3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ButtonActionPerformed
        // TODO add your handling code here:
        if (options == 0) {
            graphOptionsPanel.setVisible(false);
            previewPanel.setVisible(true);
            option3Button.setText("Set Diagram: Preview");
            graphOptsVis = false;
        }
        else {
            graphOptionsPanel.setVisible(false);
            previewPanel.setVisible(true);
            option3Button.setText("Horizon Graph: Preview");
            graphOptsVis = false;
        }
    }//GEN-LAST:event_option3ButtonActionPerformed

    private void option2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ButtonActionPerformed
        // TODO add your handling code here:
        graphOptionsPanel.setVisible(false);
        previewPanel.setVisible(true);
        graphOptsVis = false;
        if (options == 0) {
            option2Button.setText("Line Graph: Preview");
        }
        else{
            option2Button.setText("Matrix: Preview");
        }
    }//GEN-LAST:event_option2ButtonActionPerformed

    private void option1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ButtonActionPerformed
        // TODO add your handling code here:
        graphOptionsPanel.setVisible(false);
        previewPanel.setVisible(true);
        graphOptsVis = false;
        if (options == 0) {
            option1Button.setText("Bar Graph: Preview");
        }
        else {
            option1Button.setText("Scatter Plot: Preview");
        }
    }//GEN-LAST:event_option1ButtonActionPerformed

    private void recordAnswersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAnswersButtonActionPerformed
        // TODO add your handling code here:
        if (recording == true){
            recordAnswersButton.setBackground(new Color(240,240,240));
            recording = false;
        }
        else {
            recordAnswersButton.setBackground(new Color(255,51,51));
            for (int i = 0; i < listModel.getSize(); i++) {
                String listItem = (String)listModel.get(i);
                listItem = listItem.toUpperCase();
                if (listItem.contains("YES") | listItem.contains("NO")) {
                    selections.add(i);
                }
            }
            for (int i = 0; i< selections.size();i++) {
                chatList.addSelectionInterval(selections.get(i), selections.get(i));
            }
            recording = true;
        }
    }//GEN-LAST:event_recordAnswersButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setContentPane(mainPagePanel); 
        this.setResizable(false);
        this.setSize(440,350);
        this.repaint();             
        this.revalidate(); 
        System.out.println("switching frames");
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGraphButtonActionPerformed
        // TODO add your handling code here:
        this.setContentPane(graphPagePanel); 
        this.setResizable(true);
        this.setSize(600,500);
        this.repaint();             
        this.revalidate(); 
        System.out.println("switching frames");
    }//GEN-LAST:event_selectGraphButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if (!titleField.getText().equals("")) {
            graphTitleText.setText(titleField.getText());
        }
        
        if (!vAxisTitleField.getText().equals("")) {
            vAxisText.setText(vAxisTitleField.getText());
        }
        
        if (!hAxistTitleField.getText().equals("")) {
            hAxisText.setText(hAxistTitleField.getText());
        }
        System.out.println(titleField.getText());
        System.out.println(vAxisTitleField.getText());
        System.out.println(hAxistTitleField.getText());
    }//GEN-LAST:event_submitButtonActionPerformed

    private void hideMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideMenuActionPerformed
        // TODO add your handling code here:
        if (graphCust == true) {
            custimizeGraphPanel.setVisible(false);
            hideMenu.setText("Show Menu");
            graphCust = false;
        }
        else {
            custimizeGraphPanel.setVisible(true);
            hideMenu.setText("Hide Menu");
            graphCust = true;
        }
    }//GEN-LAST:event_hideMenuActionPerformed

    private void chatListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatListMouseClicked
        // TODO add your handling code here:
        if (selections.contains(chatList.getSelectedIndex())){
            selections.remove(selections.indexOf(chatList.getSelectedIndex()));
            for (int i = 0; i< selections.size();i++) {
                chatList.addSelectionInterval(selections.get(i), selections.get(i));
            }
        }
        else{ 
            selections.add(chatList.getSelectedIndex());
            for (int i = 0; i< selections.size();i++) {
                chatList.addSelectionInterval(selections.get(i), selections.get(i));
            }
        }
    }//GEN-LAST:event_chatListMouseClicked

    private void moreGraphsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreGraphsButtonActionPerformed
        // TODO add your handling code here:
        if (options == 0) {
            option2Button.setText("Matrix");
            option3Button.setText("Horizon Graph");
            option4Button.setText("Mind Map");
            option1Button.setText("Scatter Plot");
            options = 1;
        }
        else{
            option2Button.setText("Line Graph");
            option3Button.setText("Set Diagram");
            option4Button.setText("Pie Graph");
            option1Button.setText("Bar Graph");
            options = 0;
        }
    }//GEN-LAST:event_moreGraphsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(berryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(berryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(berryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(berryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new berryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JList<String> chatList;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JScrollPane chatScrollPane;
    private javax.swing.JLabel chatTitleText;
    private javax.swing.JPanel custimizeGraphPanel;
    private javax.swing.JPanel graphOptionsPanel;
    private javax.swing.JPanel graphPagePanel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel graphTitleText;
    private javax.swing.JLabel hAxisIndicator;
    private javax.swing.JLabel hAxisText;
    private javax.swing.JTextField hAxistTitleField;
    private javax.swing.JButton hideMenu;
    private javax.swing.JPanel mainPagePanel;
    private javax.swing.JButton moreGraphsButton;
    private javax.swing.JButton option1Button;
    private javax.swing.JButton option2Button;
    private javax.swing.JButton option3Button;
    private javax.swing.JButton option4Button;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JButton recordAnswersButton;
    private javax.swing.JButton selectGraphButton;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JTextField sendMessageForm;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleIndicator;
    private javax.swing.JLabel vAxisIndicator;
    private javax.swing.JLabel vAxisText;
    private javax.swing.JTextField vAxisTitleField;
    private javax.swing.JButton visualizeButton;
    private GraphPanel graph;
    // End of variables declaration//GEN-END:variables
}
